#server:
#  port: 8084
#  servlet:
#    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: admin
      password: 'admin'
 # datasource:
 #   url:  jdbc:postgresql://localhost:5432/ead-notification-v2
 #   username: postgres
 #   password: 123456
 # jpa:
 #   hibernate:
 #     ddl-auto: update
 #     dialect: org.hibernate.dialect.PostgreSQLDialect
 #     jdbc:
 #       lob.non-contextual-creation: true
 #   properties:
 #     hibernate:
 #       show_sql: true
 # output:
 #   ansi:
 #     enabled: Always
 # rabbitmq:
 #   addresses: amqps://lgzglgzz:QCdrVDcoffePpevW6Rp8T3BiuPz_zcC5@shark.rmq.cloudamqp.com/lgzglgzz


#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO

#ead:
#  broker:
#    exchange:
#      notificationCommandExchange: ead.notificationcommand
#    queue:
#      notificationCommandQueue:
#        name: ead.notificationcommand.ms.notification
#    key:
#      notificationCommandKey: ms.notification



#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - refresh
#          - health

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost

